name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 0 点同步
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/Predidit/Kazumi.git
          git fetch upstream

      - name: Sync with upstream
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          if git merge upstream/main --no-edit; then
            echo "合并成功，推送变更"
            git push origin main
          else
            echo "检测到冲突，创建PR"
            git checkout -b "sync-$(date +%s)"
            git add .
            git commit -m "解决同步冲突 $(date)" || echo "无变更可提交"
            git push origin HEAD
            # 检查是否有实际提交需要PR
            if [ "$(git log origin/main..HEAD)" != "" ]; then
              gh pr create \
                --title "上游同步: $(date +'%Y-%m-%d')" \
                --body "自动解决同步冲突" \
                --base main \
                --head $(git branch --show-current)
            else
              echo "新分支与 main 无差异，不创建 PR"
            fi
          fi